services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000

  backend_prestart:
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash scripts/prestart.sh
    env_file:
      - backend/.env.docker
    depends_on:
      - db

  backend:  
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data/:/app/backend/data
    env_file:
      - backend/.env
    depends_on:
      - db
      - backend_prestart

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: